config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :user_sessions, only: [:new, :create]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true,
  					  length: { minimum: 2 }

  scope :complete, -> { where(%Q|completed_at is not null|) }
  scope :incomplete, -> { where(completed_at: nil) }

  
  def completed?
  	!completed_at.blank?
  end
  

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	has_many :todo_items

	
	validates :title, presence: true
	validates :description, presence: true
	validates :title, length: { minimum: 3 }
	validates :description, length: { minimum: 5 }

	def has_complete_items?
		todo_items.complete.size > 0
	end

	def has_incomplete_items?
		todo_items.incomplete.size > 0
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, 	presence: true, 
						uniqueness: true,
						format: {
                   		 with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9\.-]+\.[A-Za-z]+\Z/
						}

	before_save :downcase_email

	def downcase_email
		self.email = email.downcase
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
  	if @current_user
  		true
  	else
  		redirect_to new_user_session_path, notice: %Q|You must be logged in to access this page|
  	end
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_todo_list

  def index

  end

  def new
  	@todo_item = @todo_list.todo_items.new
  end

  def create
  	@todo_item = @todo_list.todo_items.new(todo_item_params)
  	if @todo_item.save
  		flash[:success] = %Q|Added todo list item.|
  		redirect_to todo_list_todo_items_path
  	else
  		flash[:error] = %Q|There was a problem adding that todo list item.|
  		render action: :new
  	end
  end

  def edit
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def update
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = %Q|Saved todo list item.|
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = %Q|That todo item could not be saved.|
      render action: :edit
    end
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = %Q|Todo list item was deleted.|
    else
      flash[:error] = %Q|Todo list item could not be deleted.|
    end
    redirect_to todo_list_todo_items_path
  end

  def complete
     @todo_item = @todo_list.todo_items.find(params[:id])
     @todo_item.update_attribute(:completed_at, Time.now)
     redirect_to todo_list_todo_items_path, notice: %Q|Todo item marked as complete.|
  end

  def url_options
    { todo_list_id: params[:todo_list_id] }.merge(super)
  end

  private
  def find_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
  	params[:todo_item].permit(:content)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :require_user
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
	  	session[:user_id] = user.id
	  	flash[:success] = %Q|Thanks for logging in|
	  	redirect_to todo_lists_path
  	else
  		flash[:error] = %Q|Your password or email is incorrect, please check your emil and password|
  		render action: 'new'
  	end
  end
end
	

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to todo_lists_path, success: 'Thanks for signing up!' }
        #flash[:success] = %Q|Thanks for signing up!| Ver application_controller.rb para entender porqué comenté esto
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="nav">
		<h1><%= link_to %Q|Odot|, root_path %></h1>
			<ul>
				<li><%= link_to %Q|Todo Lists|, todo_lists_path %></li>
				<li><%= link_to %Q|Sign Up|, new_user_path %></li>
			</ul>
			<br class="clear" />
	</div>

	<% flash.each do |type, message| %>
		<div class="alert flash <%= type %>">
			<%= message %>
		</div>
	<% end %>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<% if @todo_item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

    <ul>
    <% @todo_item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form.label :content %>
<%= form.text_field :content %>

<%= form.submit %Q|Save| %>

app/views/todo_items/edit.html.erb
<h1><%= @todo_list.title %> - Editing Todo List Item</h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
	<%= render partial: form %>
<% end %>

app/views/todo_items/index.html.erb
<h1 class="todo-list-title"><%= @todo_list.title %></h1>
<p>Find me in app/views/todo_items/index.html.erb</p>

<table class="todo_items">
	<thead>
		<tr>
			<th width="25%">Completed?</th>
			<th width="65%">Content</th>
			<th width="10%">Operations</th>
		</tr>	
	</thead>
	<tbody>
		<% @todo_list.todo_items.each do |todo_item| %>
			<tr id="<%= dom_id(todo_item) %>" class="item">
				<td>
					<% if todo_item.completed? %>
						<%= todo_item.completed_at %>
					<% else %>
					<%= link_to "Mark Complete", complete_todo_list_todo_item_path(todo_item), method: :patch %>
					<% end %>
				</td>
				<td><%= todo_item.content %></td>
				<td>
					<%= link_to "Edit", edit_todo_list_todo_item_path(todo_item) %>
				<%= link_to "Delete", todo_list_todo_item_path(todo_item), method: :delete, data: { confirm: %Q|Are you sure?| } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<p>
	<%= link_to "New Todo Item", new_todo_list_todo_item_path %>
</p>

app/views/todo_items/new.html.erb
<h1><%= @todo_list.title %> - Creating Todo List Item</h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing todo_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Todo Lists</h1>


<% @todo_lists.each do |todo_list| %>
  <div class="todo_list" id="<%= dom_id(todo_list) %>">
    <h2><%= todo_list.title %></h2>
    <p><%= todo_list.description %></p>
    <ul class="functions">
      <li><%= link_to 'List Items', todo_list_todo_items_path(todo_list) %></li>
      <li><%= link_to 'Show', todo_list %></li>
      <li><%= link_to 'Edit', edit_todo_list_path(todo_list) %></li>
      <li><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: %Q|Are you sure?| } %></li>
    </ul>
    <br class="clear" />
  </div>
<% end %>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New todo_list</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<h1><%= @todo_list.title %></h1>

<h2><%= @todo_list.description %></h2>

<% if @todo_list.has_incomplete_items? %>
	<h3>Incomplete Items: </h3>

	<ul class="todo_items">
		<% @todo_list.todo_items.incomplete.each do |todo_item| %>
			<li><%= todo_item.content %></li>
		<% end %>
	</ul>
<% end %>

<% if @todo_list.has_complete_items? %>
	<h3>Complete Items: </h3>

	<ul class="todo_items complete-list">
		<% @todo_list.todo_items.complete.each do |todo_item| %>
			<li><%= todo_item.content %></li>
		<% end %>
	</ul>
<% end %>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>

app/views/user_sessions/new.html.erb
<h1>Log In</h1>
<%= form_tag user_sessions_path do %>
	<%= label_tag :email, "Email Address" %>
	<%= text_field_tag :email, params[:email] %>
	<br />

	<%= label_tag :password, "Password" %>
	<%= password_field_tag :password %>
	<br />

	<%= submit_tag "Log In" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, "First name" %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, "Last name" %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email, "Email" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Password" %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Password (again)" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>Register for ODOT</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>